<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /var/www/demo/docroot/civicrm_custom/extensions/uk.co.vedaconsulting.mautic/xml/schema/CRM/Mautic/MauticWebHook.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:72a131c61f30170075ca11d2939f9980)
 */

/**
 * Database access object for the MauticWebHook entity.
 */
class CRM_Mautic_DAO_MauticWebHook extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mauticwebhook';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique MauticWebHook ID
   *
   * @var int
   */
  public $id;

  /**
   * JSON serialized data received from the webhook
   *
   * @var text
   */
  public $data;

  /**
   * Mautic Webhook trigger event type.
   *
   * @var string
   */
  public $webhook_trigger_type;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $activity_id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $contact_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mauticwebhook';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'activity_id', 'civicrm_activity', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Mautic_ExtensionUtil::ts('Unique MauticWebHook ID'),
          'required' => TRUE,
          'where' => 'civicrm_mauticwebhook.id',
          'table_name' => 'civicrm_mauticwebhook',
          'entity' => 'MauticWebHook',
          'bao' => 'CRM_Mautic_DAO_MauticWebHook',
          'localizable' => 0,
        ],
        'data' => [
          'name' => 'data',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Mautic_ExtensionUtil::ts('Data'),
          'description' => CRM_Mautic_ExtensionUtil::ts('JSON serialized data received from the webhook'),
          'where' => 'civicrm_mauticwebhook.data',
          'table_name' => 'civicrm_mauticwebhook',
          'entity' => 'MauticWebHook',
          'bao' => 'CRM_Mautic_DAO_MauticWebHook',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
        ],
        'webhook_trigger_type' => [
          'name' => 'webhook_trigger_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Mautic_ExtensionUtil::ts('Webhook Trigger Type'),
          'description' => CRM_Mautic_ExtensionUtil::ts('Mautic Webhook trigger event type.'),
          'size' => CRM_Utils_Type::TWO,
          'where' => 'civicrm_mauticwebhook.webhook_trigger_type',
          'table_name' => 'civicrm_mauticwebhook',
          'entity' => 'MauticWebHook',
          'bao' => 'CRM_Mautic_DAO_MauticWebHook',
          'localizable' => 0,
          'pseudoconstant' => 'not in database',
        ],
        'activity_id' => [
          'name' => 'activity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Mautic_ExtensionUtil::ts('FK to Contact'),
          'where' => 'civicrm_mauticwebhook.activity_id',
          'table_name' => 'civicrm_mauticwebhook',
          'entity' => 'MauticWebHook',
          'bao' => 'CRM_Mautic_DAO_MauticWebHook',
          'localizable' => 0,
          'FKClassName' => 'CRM_Activity_DAO_Activity',
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Mautic_ExtensionUtil::ts('FK to Contact'),
          'where' => 'civicrm_mauticwebhook.contact_id',
          'table_name' => 'civicrm_mauticwebhook',
          'entity' => 'MauticWebHook',
          'bao' => 'CRM_Mautic_DAO_MauticWebHook',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mauticwebhook', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mauticwebhook', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
