-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

--- drop custom set and their fields
DELETE FROM `civicrm_custom_group` WHERE table_name in (
  'civicrm_value_mautic_webhook', 'civicrm_value_mautic_settings', 'civicrm_value_mautic_contact');

--- drop custom value table
DROP TABLE IF EXISTS civicrm_value_mautic_settings;
DROP TABLE IF EXISTS civicrm_value_mautic_contact;
DROP TABLE IF EXISTS civicrm_value_mautic_webhook;

SET FOREIGN_KEY_CHECKS=0;

--- drop sync table
DROP TABLE IF EXISTS `civicrm_mautic_sync`;
--- delete job entry
DELETE FROM `civicrm_job` WHERE name = 'Mautic Sync';
--- drop webhook entity table
DROP TABLE IF EXISTS `civicrm_mauticwebhook`;

SET FOREIGN_KEY_CHECKS=1;
