-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mauticwebhook`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_mauticwebhook
-- *
-- * Entity representing an incoming Mautic Webhook
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mauticwebhook` (
                                       `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MauticWebhook ID',
                                       `data` text COMMENT 'JSON serialized data received from the webhook',
                                       `webhook_trigger_type` varchar(255) COMMENT 'Mautic Webhook trigger event type.',
                                       `activity_id` int unsigned COMMENT 'FK to Contact',
                                       `contact_id` int unsigned COMMENT 'FK to Contact',
                                       `created_date` timestamp DEFAULT CURRENT_TIMESTAMP COMMENT 'When the webhook was first received by CiviCRM',
                                       `processed_date` timestamp DEFAULT NULL COMMENT 'Has this webhook been processed in CiviCRM',
                                       PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
